version: "3"
volumes:
  gitlab-runner-config:
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - ./healthcheck.sh:/healthcheck.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner
      - ../crt/gitlab.local.crt:/etc/crt/gitlab.local.crt:ro
    environment:
      - TZ=UTC
      - CA_CERTIFICATES_PATH=/etc/crt/gitlab.local.crt
    healthcheck:
      test: 'bash /healthcheck.sh gitlab-runner 3s'
      start_period: 3s
      retries: 2
      interval: 3s
      timeout: 1s
